name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      modules: '["test_charm", "test_proxy", "test_cos", "test_database", "test_db_migration", "test_default"]'
      juju-channel: 3.3/stable
      channel: 1.29-strict/stable
